package alphadelete.aguaconsciente.ui.activities;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.view.ViewPager;
import android.support.v7.widget.Toolbar;
import android.view.View;

import com.astuetz.PagerSlidingTabStrip;

import alphadelete.aguaconsciente.R;
import alphadelete.aguaconsciente.ui.fragments.ReportLastMonthsFragment;
import alphadelete.aguaconsciente.ui.fragments.ReportTotalFragment;

public class ReportsActivity extends BaseParentActivity {
    private PagerSlidingTabStrip tabs;
    private ViewPager pager;

    private int mCurrentSelectedScreen;
    private int mNextSelectedScreen;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // Create Activity based on XML layout
        setContentView(R.layout.activity_reports);

        // Override super method after the super
        super.onCreate(savedInstanceState);

        // Set the Tabs Manager
        pager = (ViewPager) findViewById(R.id.timer_pager);
        pager.setAdapter(new MyAdapter(getSupportFragmentManager()));
        tabs = (PagerSlidingTabStrip) findViewById(R.id.tabs);
        tabs.setViewPager(pager);
        tabs.setOnPageChangeListener(
            new ViewPager.OnPageChangeListener() {
                @Override
                public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                    if ( position == mCurrentSelectedScreen )
                    {
                        // We are moving to next screen on right side
                        if ( positionOffset > 0.1 )
                        {
                            mNextSelectedScreen = position + 1;
                            //Way to get TagName which generated by FragmentPagerAdapter
                            String tagName = "android:switcher:" + R.id.timer_pager + ":" + 1; // Your pager name & tab no of Second Fragment
                            //Get SecondFragment object from FirstFragment
                            ReportLastMonthsFragment fragLastMonths = (ReportLastMonthsFragment) getSupportFragmentManager().findFragmentByTag(tagName);
                            fragLastMonths.animateChart();
                        }
                    }
                    else
                    {
                        // We are moving to next screen left side
                        if ( positionOffset > 0.1 )
                        {
                            mNextSelectedScreen = position + 1;
                            //Way to get TagName which generated by FragmentPagerAdapter
                            String tagName = "android:switcher:" + R.id.timer_pager + ":" + 0; // Your pager name & tab no of Second Fragment
                            //Get SecondFragment object from FirstFragment
                            ReportTotalFragment fragTotal = (ReportTotalFragment) getSupportFragmentManager().findFragmentByTag(tagName);
                            fragTotal.animateChart();
                        }
                    }
                }

                @Override
                public void onPageSelected(int i) {
                    mCurrentSelectedScreen = i;
                    mNextSelectedScreen = i;
                }

                @Override
                public void onPageScrollStateChanged(int i) {

                }
            }
        );

        // Set toolbar as Actionbar
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        toolbar.setPopupTheme(R.style.ThemeOverlay_AppCompat_Light);
        if (toolbar != null) {
            setSupportActionBar(toolbar);
            // Set back button and back action
            toolbar.setNavigationIcon(R.drawable.ic_back_button);
            toolbar.setNavigationOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    onBackPressed();
                }
            });
        }

    }

    public class MyAdapter extends FragmentPagerAdapter {
        private String[] titles = { getString(R.string.tab_reports_total),
                getString(R.string.tab_reports_last_12) };

        public MyAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
            switch(position){
                case 0:{
                    return ReportTotalFragment.newInstance(position);
                }
                case 1:{
                    return ReportLastMonthsFragment.newInstance(position);
                }
            }
            return null;
        }

        @Override
        public int getCount() {
            return titles.length;
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return titles[position];
        }

    }


    @Override
    public void onResume() {
        super.onResume();
    }
}
